### ISSUE TITLE
Conda-forge release?

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdaencore#23]
Looks like things are on pypi now, can we aim for a conda-forge package?

**Comment by orbeckst** [comment]
@ianmkenney can you get started on the conda-forge process?

**Comment by IAlibay** [comment]
@ianmkenney 'll take this on.

**Comment by orbeckst** [comment]
In progress on conda-forge PR https://github.com/conda-forge/staged-recipes/pull/24019

**Comment by orbeckst** [comment]
We now have the feedstock: https://github.com/conda-forge/mdaencore-feedstock — hooray 🎉 and the 0.1.0 conda-forge package https://anaconda.org/conda-forge/mdaencore
