### ISSUE TITLE
Using OpenMP parallelization on Windows 10

### ISSUE THREAD

**Issue by tanoury1** [MDAnalysis/mdaencore#27]
Hi,
I am using MDAnalysis on my Windows 10 laptop and was trying to run a clustering method on 4 cores as shown below.  However, it only runs on a single core.  What am I overlooking?

ces1, details1 = encore.ces([u1], select='index 0:55', clustering_method=clustering_method, ncores=4)

Thank you,
Jerry

**Comment by mtiberti** [comment]
hi, as far as we remember there's no parallelisation on the single method - it only happens when using clustering methods with multiple set of parameters (each set is run independently). In that case this would be the expected behaviour

**Comment by orbeckst** [comment]
As this is currently expected behavior, I am closing this issue.

If this is a feature request, please open it again or open a new one with details of what you'd want to see.
