### ISSUE TITLE
Citation path in __init__.py

### ISSUE THREAD

**Issue by ianmkenney** [MDAnalysis/mdaencore#4]
The __init__.py for mdaencore, since it was taken from MDA core, uses `MDAnalysis.analysis.encore`. What should this be changed to, if anything?

**Comment by orbeckst** [comment]
You mean https://github.com/MDAnalysis/mdaencore/blob/c6893dd3e342b28af0f93248d0f572991566f020/mdaencore/__init__.py#L41 

I think this should become "mdaencore".

**Comment by ianmkenney** [comment]
Sounds good, figured I'd be cautious with anything publication related

**Comment by orbeckst** [comment]
Closed via 8121e12

**Comment by orbeckst** [comment]
Reopening --- this commit hadn't been merged for whatever reasons. Sorry.
