### ISSUE TITLE
Add ReadTheDocs

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdaencore#9]
## Is your feature request related to a problem? ##

Having RTD online makes it a lot easier to preview and debug documentation. Many of our repos have RTD and there's already a config file in this repo.

## Describe the solution you'd like ##

Could you please add RTD support for `main` and PRs?

**Comment by lilyminium** [comment]
cc https://github.com/MDAnalysis/mdanalysis-sphinx-theme/issues/25, https://github.com/MDAnalysis/mdaencore/pull/1#issuecomment-1688929514

**Comment by lilyminium** [comment]
The docs badge in the README also links to RTD docs.

**Comment by orbeckst** [comment]
> The docs badge in the README also links to RTD docs.

Should point to https://www.mdanalysis.org/mdaencore/
